Repository openshift-knative/eventing-istio, pull requests merged in 2024-08, with the labels that each got.

#269 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-istio-release-next-knative-eventing-istio-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-istio-release-next-knative-eventing-istio-controller.yaml
  .konflux/applications/serverless-operator-release-next/serverless-operator-release-next.yaml
  .tekton/docker-build-oci-ta.yaml
  .tekton/knative-eventing-istio-controller-release-next-pull-request.yaml
  .tekton/knative-eventing-istio-controller-release-next-push.yaml
Labels: approved, lgtm

#270 Checkout Konflux configurations on update-to-head too
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#271 [release-v1.14] update go to 1.22
  go.mod
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/generate.sh
Labels: approved

#279 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-istio-release-next-knative-eventing-istio-controller.yaml
Labels: approved, lgtm

#280 [main] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/knative-eventing-istio-controller-release-next-pull-request.yaml
  .tekton/knative-eventing-istio-controller-release-next-push.yaml
Labels: approved, lgtm

#284 [release-v1.15] rerun openshift/generate.sh
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
Labels: lgtm
