Repository openshift-knative/eventing-istio, pull requests merged in 2025-02, with the labels that each got.

#405 [release-v1.17] Update Konflux configurations
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-eventing-istio-controller-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-eventing-istio-controller-117.yaml
  .tekton/docker-build.yaml
  .tekton/kn-eventing-istio-controller-117-pull-request.yaml
  .tekton/kn-eventing-istio-controller-117-push.yaml
Labels: needs-ok-to-test

#392 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#406 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
Labels: needs-ok-to-test

#394 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
Labels: needs-ok-to-test

#393 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
Labels: approved, lgtm, needs-ok-to-test

#415 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#476 [release-v1.16] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, needs-ok-to-test

#483 [release-v1.15] Run hack generate tool directly
  openshift/generate.sh
  openshift/install.sh
Labels: approved, lgtm

#486 [main] Update dependabot configurations
  renovate.json
Labels: approved, lgtm, needs-ok-to-test
